<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-5CK4J9DQ" failures="1" tests="3" name="com.phonelcdparts.registrationTest.RegistrationTest" time="22.031" errors="0" timestamp="2023-12-07T00:56:40 EST" skipped="1">
  <testcase classname="com.phonelcdparts.registrationTest.RegistrationTest" name="aloRegistrationTest" time="12.072"/>
  <system-out/>
  <testcase classname="com.phonelcdparts.registrationTest.RegistrationTest" name="sokalRegistrationTest" time="6.281">
    <failure message="expected [Create New Customer Account] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Create New Customer Account] but found [hello]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.phonelcdparts.registrationTest.RegistrationTest.sokalRegistrationTest(RegistrationTest.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </failure>
  </testcase> <!-- sokalRegistrationTest -->
  <system-out/>
  <testcase classname="com.phonelcdparts.registrationTest.RegistrationTest" name="testSkiped" time="3.678">
    <skipped/>
  </testcase> <!-- testSkiped -->
  <system-out/>
</testsuite> <!-- com.phonelcdparts.registrationTest.RegistrationTest -->
